sudo: required
language: java
jdk: openjdk8
services: docker
script: mvn clean verify
after_success:
- bash usermanagement/deploy.sh
deploy:
  skip_cleanup: true
  provider: openshift
  user: torsten.compart@gmail.com
  password:
    secure: YRyy6WhfkSt+5toksCnWBWMqUo1ZeXfw8/DJFMXD3gDnX7TRpkXXjBDHPoHpTlfE26BuXc7e8RmDxHk+GF4DjPE1VtzvyPiQ8u2LkjwIpUblhigNb8X1uwvBnoRcWHxhqddEnYr6+ZdODx9SRMWRGHNIrt1LhVFfvctr2j0yyDnYRSKp8jZ3P7QjDMUv0Q96E7lcjjoFeI2rmAOfuFnt6cP/r9Bb84b5gyI7z1ifRbp7mdWOkiEnaryCrfumjWZ16K5p36FP3s/hh97oPVymTcfblxkgiD8flp5M+9Q3o6c7tFJtHGWHD+teGdNlGadYkVL8J4J8YHgpV9JktRchJoykE/AW0NZSIrqt8kgawnSvDavL+Qhzp5088JHHgUkcLWpWyzUS/rODEhHB1gaU76+35naIr3mxosAFC2jw+NWzhb7O0DqYXiEyd/lTm1b84EEJtpktmApnAf4BJuTvV6jy/k7uBL6O7Y7WVZyCv8lpABeJvehSRKkgzrfMc2T2iKZPvrEBeLvVjRbmQ03GHdcie5Q7EWU2uFTPbmNu3f94tUt4pR+YI6lyYIbboUqRBobmD9fr9j5Ui5LEGY6xeCLLpCnpEHKav1FZ35ZxZ2FwUDcB4aZznDlX2OzXyEVP67N4BA19In9tv4FO3cIb1iY9IDcnGxa25DvrC/jsdWs=
  app: nicoco
  domain: nicoco
