angular.module('nicoco').value('loveStories', [
	{src: 'images/lovestories/1.jpg', desc: ''},
	{src: 'images/lovestories/2.jpg', desc: ''},
	{src: 'images/lovestories/3.jpg', desc: ''},
	{src: 'images/lovestories/4.jpg', desc: ''},
	{src: 'images/lovestories/5.jpg', desc: ''},
	{src: 'images/lovestories/6.jpg', desc: ''},
	{src: 'images/lovestories/7.jpg', desc: ''},
	{src: 'images/lovestories/8.jpg', desc: ''},
	{src: 'images/lovestories/9.jpg', desc: ''},
	{src: 'images/lovestories/10.jpg', desc: ''},
	{src: 'images/lovestories/11.jpg', desc: ''},
	{src: 'images/lovestories/12.jpg', desc: ''},
	{src: 'images/lovestories/13.jpg', desc: ''},
	{src: 'images/lovestories/14.jpg', desc: ''},
	{src: 'images/lovestories/15.jpg', desc: ''},
	{src: 'images/lovestories/16.jpg', desc: ''},
	{src: 'images/lovestories/17.jpg', desc: ''},
	{src: 'images/lovestories/18.jpg', desc: ''},
	{src: 'images/lovestories/19.jpg', desc: ''},
	{src: 'images/lovestories/20.jpg', desc: ''},
	{src: 'images/lovestories/21.jpg', desc: ''},
	{src: 'images/lovestories/22.jpg', desc: ''},
	{src: 'images/lovestories/23.jpg', desc: ''},
	{src: 'images/lovestories/24.jpg', desc: ''}
]);
